config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :filters_values
  resources :filters
  resources :filters
  resources :category_fields
  resources :categories
  resources :cities
  resources :bookings
  resources :reviews
  resources :items
  resources :users
  resources :bookings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  get 'about' => 'pages#about', as: 'about'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates :item_id, :user_id, presence: true
  validates :started_at, date: true
  validates :ended_on,
            date: { after: :started_at }
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry
  has_many :items, dependent: :destroy
  has_and_belongs_to_many :filters, dependent: :destroy
  has_many :category_fields, inverse_of: :category, dependent: :destroy
  accepts_nested_attributes_for :category_fields,
                                reject_if: :all_blank, allow_destroy: true

  validates :name, :filters, presence: true
end

app/models/category_field.rb
class CategoryField < ActiveRecord::Base
  belongs_to :category

  validates :filter, :value, presence: true
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users, dependent: :destroy
  has_many :items, through: :users, dependent: :destroy

  validates :name, presence: true
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  has_many :filters_values, dependent: :destroy
  has_and_belongs_to_many :categories

  validates :name, presence: true
end

app/models/filters_value.rb
class FiltersValue < ActiveRecord::Base
  belongs_to :filter
  has_and_belongs_to_many :items

  validates :option, :filter_id, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :reviews, as: :reviewable, dependent: :destroy
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_and_belongs_to_many :filters_values

  validates :name, :category_id, :user_id, presence: true

  scope :by_name, ->(name) { where('name LIKE ?', "%#{name}%") }
  scope :by_category, ->(category_id) { where(category_id: category_id) }
  scope :by_option, lambda { |filters_value_id|
    joins(:filters_values).where(filters_values: { id: filters_value_id })
  }
  scope :price_range, lambda { |price, days|
    where(Item.arel_table[:daily_price].lteq(price / days))
  }

  def self.test1(start_date, end_date)
    ids = joins(:bookings).where(Booking.arel_table[:started_at].lteq(end_date))
                          .where(Booking.arel_table[:ended_on].gteq(start_date))
                          .ids
    Item.where.not(id: ids)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :reviewable, polymorphic: true, required: true


  validates :user_id, :message, presence: true
  validate :must_be_booking
  def must_be_booking
    if reviewable.is_a?(Item)
      return if Booking.exists?(user_id: user_id, item_id: reviewable_id)
      errors.add(:reviewable, 'You have not booked')
    elsif reviewable.is_a?(User)
      return if User.joins(bookings: :item)
                    .exists?(users: { id: user_id },
                             items: { user_id: reviewable_id })
      errors.add(:reviewable, 'You are not trading')
    end
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :category

  def search_items
    items = Item.order(:name)
    items = items.where('name LIKE ?', "%#{keywords}%") if keywords.present?
    items = items.where(category_id: category_id) if category_id.present?
    items = items.joins(:filters_values).where(filters_values: { id: filters_value_id } ) if filters_value_id.present?
    return items
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :items, dependent: :destroy
  belongs_to :city
  has_many :items_reviews, through: :items, source: :reviews, dependent: :destroy

  validates :name, :city_id, presence: true
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  def index
    @items = Item.all.paginate(page: params[:page], per_page: 5)
    @items = @items.by_name(params[:name]) if params[:name].present?
    @items = @items.by_category(params[:category_id]) if params[:category_id].present?
    @items = @items.by_option(params[:filters_value_id]) if params[:filters_value_id].present?
  end

  def new
    @item = Item.new
  end

  def show; end

  def edit; end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:user_id, :name, :category_id, :days)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page'
  end

  def index
    @title = 'TravelMateBlog'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def show; end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %>
    <%= f.collection_select :user_id, User.order(:name), :id, :name, prompt: '' %>
  </div>
  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, prompt: '' %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<% if item.user.present? %>
  <p>
    <strong>User:</strong>
    <%= item.user.name%>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= item.name %>
</p>

<td><%= link_to 'Show', item %></td>
<td><%= link_to 'Edit', edit_item_path(item) %></td>
<td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

<hr>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Listing Items</h1>

<%= render 'shared/submenu' %>

<hr>

<%= form_tag items_path, :method => 'get' do %>
  <%= text_field_tag :name, params[:name], placeholder: 'Enter search term name...' %>
  <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), include_blank: true %>
  <%= select_tag :filters_value_id, options_from_collection_for_select(FiltersValue.all, :id, :option, params[:filters_value_id]), include_blank: true %>
  <%= submit_tag "Search" %>
<% end %>

<%= link_to "Advanced Search", new_search_path%>
<hr>

<%=  link_to 'New Item', new_item_path %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Category</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td>
          <% if item.user.present? %>
            <%= item.user.name %>
          <% end %>
        </td>
        <td><%= item.name %></td>
        <td>
          <% if item.category.present? %>
            <%= item.category.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @items %>
  </div>
  <%= will_paginate @items, :container => false %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<% if @item.user.present? %>
  <p>
    <strong>User:</strong>
    <%= @item.user.name%>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<% if @item.category.present? %>
  <p>
    <strong>Category:</strong>
    <%= @item.category.name %>
  </p>
<% end %>

<% if @item.reviews.present? %>
  <strong>Reviews:</strong>
  <% @item.reviews.each do |reviews| %><br>
    <%= "» " %><%= reviews.message %>
  <% end %>
<% end %>

<br><br>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.collection_select :city_id, City.order(:name), :id, :name, prompt: '' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Users</h1>

<%= link_to 'New User', new_user_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>
          <% if user.city.present? %>
            <%= user.city.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <div class="apple_pagination">
      <div class="page_info">
        <%= page_entries_info @users %>
      </div>
      <%= will_paginate @users, :container => false %>
    </div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<% if @user.city.present? %>
  <p>
    <strong>From:</strong>
    <%= @user.city.name %>
  </p>
<% end %>

<% if @user.reviews.present? %>
<p>
  <strong>Reviews:</strong>
  <% @user.reviews.each do |reviews| %><br>
    <%= "» " %><%= reviews.message %>
  <% end %>
</p>
<% end %>

<% if @user.items.present? %>
  <p>
    <strong>Items:</strong>
    <% @user.items.each do |items| %>
      <%= items.name %> |
    <% end %>
  </p>
<% end %>

<% if @user.bookings.present? %>
  <p>
    <strong>Bookings:</strong>
    <% @user.bookings.each do |bookings| %>
      <%= bookings.item.name %><%= " » Ended on: " %><%= bookings.ended_on %>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>